### ISSUE TITLE
Criar branch 9.5 - dev

### ISSUE THREAD

**Issue by verdanatech-luana** [verdanatech/fusioninventory#1]
Dentro do arquivo no vscode criar novas branchs 9.5 - dev 

![2021-08-16_11-49](https://user-images.githubusercontent.com/86842154/129583242-e4a04b19-97b4-4d3e-8c86-28d0cea7bc71.png)

**Comment by verdanatech-luana** [comment]
Branch 9.5-dev criada

![2021-08-16_13-32](https://user-images.githubusercontent.com/86842154/129598139-dc33f980-0e91-4086-a8f0-eff8f6d85e9d.png)

![2021-08-16_13-34](https://user-images.githubusercontent.com/86842154/129598165-d9054a45-a072-4a00-a6ed-f0019464d81d.png)

**Comment by verdanatech-marcio** [comment]
Testado, funcionando no GLPI - 9.5.
![TesteFI](https://user-images.githubusercontent.com/80538863/129727276-7b674d17-671f-4d4d-a1d3-777375603166.png)
